# Generated by Django 4.2.2 on 2023-06-17 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 17, 12, 45, 16, 775174), verbose_name='Due Date'),
        ),
    ]
