# Generated by Django 4.2.2 on 2023-06-17 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0002_alter_loan_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='comment',
            field=models.TextField(default='', verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 17, 12, 59, 27, 43941), verbose_name='Due Date'),
        ),
    ]
